[package]
name = "lasso_rust"
version = "0.1.0"
authors = ["Kieran Elmes <kelmes@caelus.nz>"]
edition = "2018"

[dependencies]
csv = "1.1"
clap = "2.33.0"
bitpacking = "0.8.2"
rand = "0.7.2"
rayon = "1.3.0"
crossbeam-utils = "0.7.0"

[profile.release]
debug = true
