default:
	clang -lgsl -L/usr/include/gsl -Wall -lgslcblas -lm -I/usr/local/include break_gsl.c -o clang_break_gsl -O0
	gcc -lgsl -L/usr/include/gsl -Wall -lgslcblas -lm -I/usr/local/include break_gsl.c -o gcc_break_gsl -O0
